//Java Nested Try Example
public class JavaExceptionExample
{
    public static void main(String [] args){
        try{
            try{
                System.out.println("going to divide");
                int b = 39/0;
            }
            catch(ArithmeticException e){System.out.println(e);}
            try{
                int a[] = new int [5];
                a[5] = 4;
            }
            catch(ArrayIndexOutOfBoundsException a){System.out.println(a);}
            System.out.println("oder statement:");
            
        }
    catch(Exception t){System.out.println("handeled");}
   
    System.out.println("normal flow...");
    }
}
